version: "3"
services:
       message-manager-docker:
           container_name: message-manager-docker
           image: shahaelbaz1/message-manager-docker
           restart: always
           build: .
           ports:
             - "3000:3000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'